"""Purchase-order outputs: a supplier-upload CSV and a PDF PO for ISO records.

CSV is one generic layout for every supplier (Supplier Part No, Manufacturer Part No, Quantity,
Description, Unit Price, Reference). The PDF is a self-contained document headed with the company
profile (Setup → Company details).
"""

from __future__ import annotations

import csv
import io

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from ...core.db import Database

CSV_HEADER = ["Supplier Part No", "Manufacturer Part No", "Quantity",
              "Description", "Unit Price", "Reference"]

# fpdf core fonts are latin-1 only; map common non-latin-1 symbols, replace the rest.
_REPL = {"—": "-", "–": "-", "‘": "'", "’": "'", "“": '"',
         "”": '"', "Ω": "ohm", "→": "->", "•": "-"}


def _s(v) -> str:
    s = str(v if v is not None else "")
    for bad, good in _REPL.items():
        s = s.replace(bad, good)
    return s.encode("latin-1", "replace").decode("latin-1")


def _company(db: Database) -> dict:
    """Company profile (Setup → Company details) for the PDF header. Resilient if the
    settings table isn't present (returns an empty profile rather than failing)."""
    try:
        with db.connect() as conn:
            rows = dict(conn.execute(
                "SELECT key, value FROM app_settings WHERE key LIKE 'company.%'").fetchall())
    except Exception:
        return {}
    return {k[len("company."):]: (v or "") for k, v in rows.items()}


def po_csv(po: dict) -> str:
    """A generic supplier-upload CSV for a purchase order (returns the text)."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(CSV_HEADER)
    for ln in po["lines"]:
        writer.writerow([
            ln.get("supplier_pno") or "",
            ln.get("mfr_pno") or "",
            _qty(ln.get("qty")),
            ln.get("description") or ln.get("value") or "",
            _qty(ln.get("unit_price")),
            ln.get("part_no") or "",
        ])
    return buf.getvalue()


def _qty(v):
    if v is None:
        return ""
    return f"{v:g}" if isinstance(v, float) else v


class _POPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, "PURCHASE ORDER", align="R")
        self.ln(12)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(120)
        self.cell(0, 8, "Generated by PartPilot - retained for ISO records", align="C")


def po_pdf(po: dict, company: dict) -> bytes:
    pdf = _POPDF(orientation="L", unit="mm", format="A4")  # landscape so all columns fit comfortably
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    epw = pdf.w - pdf.l_margin - pdf.r_margin

    # Issuer (our company) block.
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(20)
    pdf.cell(0, 6, _s(company.get("name") or "Your company"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(70)
    blocks = [company.get("address"), _join(company, "postcode", "city"), company.get("country"),
              _kv("VAT", company.get("vat_no")), _kv("Org no", company.get("org_no")),
              _join_sep(company.get("email"), company.get("phone"), company.get("website"))]
    for block in blocks:
        for line in (block or "").splitlines():
            if line.strip():
                pdf.cell(0, 5, _s(line.strip()), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    # Supplier + PO meta.
    pdf.set_text_color(20)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "Supplier", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 5, _s(po.get("supplier_name") or "-"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)
    for label, value in [("PO number", po.get("po_no") or f"PO-{po['id']}"),
                         ("Order date", po.get("order_date") or ""),
                         ("Required date", po.get("required_date") or ""),
                         ("Currency", po.get("currency") or "")]:
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(32, 5, f"{label}:")
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 5, _s(value), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    # Line table.
    widths = [0.16, 0.20, 0.10, 0.30, 0.12, 0.12]
    cols = ["Supplier P/N", "MPN", "Qty", "Description", "Unit", "Line total"]
    aligns = ["L", "L", "R", "L", "R", "R"]
    pdf.set_fill_color(235, 238, 243)
    pdf.set_font("Helvetica", "B", 8.5)
    for w, c, a in zip(widths, cols, aligns):
        pdf.cell(w * epw, 7, c, border="B", align=a, fill=True)
    pdf.ln(7)

    pdf.set_font("Helvetica", "", 8.5)
    total = 0.0
    for ln in po["lines"]:
        qty, price = ln.get("qty") or 0, ln.get("unit_price") or 0
        line_total = qty * price
        total += line_total
        cells = [ln.get("supplier_pno") or "", ln.get("mfr_pno") or "", f"{qty:g}",
                 (ln.get("description") or ln.get("value") or "")[:80],
                 f"{price:.4f}" if ln.get("unit_price") is not None else "", f"{line_total:.2f}"]
        for w, val, a in zip(widths, cells, aligns):
            pdf.cell(w * epw, 6, _s(val), border="B", align=a)
        pdf.ln(6)

    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(sum(widths[:-1]) * epw, 7, "Total", align="R")
    cur = f" {po['currency']}" if po.get("currency") else ""
    pdf.cell(widths[-1] * epw, 7, _s(f"{total:.2f}{cur}"), align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    if po.get("notes"):
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 5, "Notes", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5, _s(po["notes"]))

    return bytes(pdf.output())


def _join(c, *keys):
    return " ".join(c.get(k) or "" for k in keys).strip()


def _join_sep(*vals):
    return "  -  ".join(v for v in vals if v)


def _kv(label, value):
    return f"{label}: {value}" if value else ""
