"""Goods-received-note outputs: a CSV line list and a PDF GRN for ISO records.

A GRN is an immutable record once received, so these are rendered on demand from the stored receipt
(no separate archive table needed). Mirrors the purchase-order exports and reuses their company
header + latin-1 sanitiser so the two documents look like one family.
"""

from __future__ import annotations

import csv
import io

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from ..purchase_orders.export import _company, _s  # shared company block + latin-1 sanitiser

# Re-exported so the router can build the company header without reaching into another feature.
company_profile = _company

CSV_HEADER = ["Part No", "Value", "Qty received", "Unit Price", "Line Value"]


def _num(v):
    if v is None:
        return ""
    return f"{v:g}" if isinstance(v, float) else v


def grn_csv(g: dict) -> str:
    """A line list for a goods receipt (returns the text)."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(CSV_HEADER)
    for ln in g["lines"]:
        writer.writerow([
            ln.get("part_no") or "",
            ln.get("value") or "",
            _num(ln.get("qty")),
            _num(ln.get("unit_price")),
            _num(ln.get("line_value")),
        ])
    return buf.getvalue()


class _GRNPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, "GOODS RECEIVED NOTE", align="R")
        self.ln(12)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(120)
        self.cell(0, 8, "Generated by PartPilot - retained for ISO records", align="C")


def grn_pdf(g: dict, company: dict) -> bytes:
    pdf = _GRNPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    epw = pdf.w - pdf.l_margin - pdf.r_margin

    # Receiver (our company) block.
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(20)
    pdf.cell(0, 6, _s(company.get("name") or "Your company"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(70)
    for line in (company.get("address") or "").splitlines():
        if line.strip():
            pdf.cell(0, 5, _s(line.strip()), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    loc = " ".join(x for x in (company.get("postcode"), company.get("city")) if x)
    if loc:
        pdf.cell(0, 5, _s(loc), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    if company.get("country"):
        pdf.cell(0, 5, _s(company["country"]), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    # Supplier + GRN meta.
    pdf.set_text_color(20)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "Supplier", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 5, _s(g.get("supplier_name") or "-"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)
    for label, value in [("GRN number", g.get("grn_no") or f"GRN-{g['id']}"),
                         ("Received", g.get("grn_date") or ""),
                         ("Against PO", g.get("po_no") or ""),
                         ("Advice / delivery note", g.get("advice_no") or ""),
                         ("Received by", g.get("received_by") or "")]:
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(46, 5, f"{label}:")
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 5, _s(value), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    # Line table.
    widths = [0.22, 0.36, 0.14, 0.14, 0.14]
    cols = ["Part No", "Value", "Qty recv", "Unit", "Line value"]
    aligns = ["L", "L", "R", "R", "R"]
    pdf.set_fill_color(235, 238, 243)
    pdf.set_font("Helvetica", "B", 8.5)
    for w, c, a in zip(widths, cols, aligns):
        pdf.cell(w * epw, 7, c, border="B", align=a, fill=True)
    pdf.ln(7)

    pdf.set_font("Helvetica", "", 8.5)
    total = 0.0
    for ln in g["lines"]:
        qty = ln.get("qty") or 0
        price = ln.get("unit_price")
        lv = ln.get("line_value")
        if lv is not None:
            total += lv
        cells = [ln.get("part_no") or "-", (ln.get("value") or "")[:60], f"{qty:g}",
                 f"{price:.4f}" if price is not None else "",
                 f"{lv:.2f}" if lv is not None else ""]
        for w, val, a in zip(widths, cells, aligns):
            pdf.cell(w * epw, 6, _s(val), border="B", align=a)
        pdf.ln(6)

    if total:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(sum(widths[:-1]) * epw, 7, "Total value", align="R")
        pdf.cell(widths[-1] * epw, 7, _s(f"{total:.2f}"), align="R",
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return bytes(pdf.output())
