"""Customer-order output: a PDF order acknowledgement sent to the customer and retained for ISO.

The acknowledgement confirms the order back to the customer (their reference, the lines, prices and
totals). It is headed with our company profile (Setup -> Company details) and addressed to the
customer. Frozen and stored immutably in ``co_documents`` when the order is acknowledged.
"""

from __future__ import annotations

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from ...core.db import Database

# fpdf core fonts are latin-1 only; map common non-latin-1 symbols, replace the rest.
_REPL = {"—": "-", "–": "-", "‘": "'", "’": "'", "“": '"',
         "”": '"', "Ω": "ohm", "→": "->", "•": "-", "−": "-"}


def _s(v) -> str:
    s = str(v if v is not None else "")
    for bad, good in _REPL.items():
        s = s.replace(bad, good)
    return s.encode("latin-1", "replace").decode("latin-1")


def _company(db: Database) -> dict:
    """Company profile (Setup -> Company details) for the PDF header. Resilient if the
    settings table isn't present (returns an empty profile rather than failing)."""
    try:
        with db.connect() as conn:
            rows = dict(conn.execute(
                "SELECT key, value FROM app_settings WHERE key LIKE 'company.%'").fetchall())
    except Exception:
        return {}
    return {k[len("company."):]: (v or "") for k, v in rows.items()}


class _AckPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, "ORDER ACKNOWLEDGEMENT", align="R")
        self.ln(12)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(120)
        self.cell(0, 8, "Generated by PartPilot - retained for ISO records", align="C")


def ack_pdf(order: dict, company: dict) -> bytes:
    pdf = _AckPDF(orientation="L", unit="mm", format="A4")  # landscape so all columns fit comfortably
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    epw = pdf.w - pdf.l_margin - pdf.r_margin

    # Party blocks side by side: us (FROM) on the left, then the invoice and (if different) the
    # delivery address. Falls back to the customer's base address when no structured address is set.
    cust = order.get("customer") or {}
    cust_name = order.get("customer_name") or "-"

    columns = [("From", company.get("name") or "Your company", _flatten(
        company.get("address"), _join(company, "postcode", "city"), company.get("country"),
        _kv("VAT", company.get("vat_no")), _kv("Org no", company.get("org_no")),
        company.get("email"), company.get("phone"), company.get("website")))]

    invoice = order.get("invoice_address")
    delivery = order.get("delivery_address")
    if invoice or delivery:
        inv_name, inv_lines = _addr_party(invoice, cust, cust_name)
        columns.append(("Invoice to", inv_name, inv_lines))
        # Show a separate Deliver-to only when it's a different address.
        if delivery and not (invoice and delivery.get("id") == invoice.get("id")):
            dlv_name, dlv_lines = _addr_party(delivery, cust, cust_name)
            columns.append(("Deliver to", dlv_name, dlv_lines))
    else:  # legacy order with only the base address
        columns.append(("To", cust_name, _addr_party(None, cust, cust_name)[1]))

    top = pdf.get_y()
    n = len(columns)
    gap = epw * 0.03
    col_w = (epw - gap * (n - 1)) / n
    ends = []
    for i, (heading, name, lines) in enumerate(columns):
        x = pdf.l_margin + i * (col_w + gap)
        ends.append(_party(pdf, x, top, col_w, heading, name, lines))

    pdf.set_xy(pdf.l_margin, max(ends) + 3)

    # Order meta.
    pdf.set_text_color(20)
    for label, value in [("Order ref", order.get("order_ref") or f"CO-{order['id']}"),
                         ("Your PO", order.get("customer_po") or ""),
                         ("Order date", order.get("order_date") or ""),
                         ("Required date", order.get("required_date") or ""),
                         ("Currency", order.get("currency") or "")]:
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(32, 5, f"{label}:")
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 5, _s(value), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    # Line table.
    widths = [0.06, 0.22, 0.28, 0.09, 0.13, 0.08, 0.14]
    cols = ["#", "Product", "Description", "Qty", "Unit", "Disc %", "Line total"]
    aligns = ["R", "L", "L", "R", "R", "R", "R"]
    pdf.set_fill_color(235, 238, 243)
    pdf.set_font("Helvetica", "B", 8.5)
    for w, c, a in zip(widths, cols, aligns):
        pdf.cell(w * epw, 7, c, border="B", align=a, fill=True)
    pdf.ln(7)

    pdf.set_font("Helvetica", "", 8.5)
    for i, ln in enumerate(order["lines"], start=1):
        qty = ln.get("ordered_qty") or 0
        price = ln.get("unit_price")
        disc = ln.get("discount_percent")
        cells = [str(ln.get("line_no") or i), ln.get("part_no") or "",
                 (ln.get("value") or "")[:70], f"{qty:g}",
                 f"{price:.4f}" if price is not None else "",
                 f"{disc:g}" if disc else "", f"{ln.get('line_total') or 0:.2f}"]
        for w, val, a in zip(widths, cells, aligns):
            pdf.cell(w * epw, 6, _s(val), border="B", align=a)
        pdf.ln(6)

    # Totals.
    cur = f" {order['currency']}" if order.get("currency") else ""
    label_w = sum(widths[:-1]) * epw
    tw = widths[-1] * epw

    def total_row(label, value, bold=False):
        pdf.set_font("Helvetica", "B" if bold else "", 9.5 if bold else 9)
        pdf.cell(label_w, 6, label, align="R")
        pdf.cell(tw, 6, _s(value), align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(1)
    total_row("Goods subtotal", f"{order.get('subtotal') or 0:.2f}")
    if order.get("discount_amount"):
        total_row("Order discount", f"-{order['discount_amount']:.2f}")
    if order.get("delivery"):
        total_row("Delivery", f"{order['delivery']:.2f}")
    if order.get("tax"):
        total_row("Tax", f"{order['tax']:.2f}")
    total_row("Order total", f"{order.get('grand_total') or 0:.2f}{cur}", bold=True)

    if order.get("notes"):
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 5, "Notes", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5, _s(order["notes"]))

    return bytes(pdf.output())


def _addr_party(addr: dict | None, cust: dict, fallback_name: str) -> tuple[str, list[str]]:
    """Return (name, detail-lines) for a party block, from a structured address row when present,
    else from the contact's base address."""
    if addr:
        city_region = ", ".join(p for p in (addr.get("city"), addr.get("region")) if p)
        return (addr.get("company") or fallback_name, _flatten(
            addr.get("contact"), addr.get("line1"), addr.get("line2"), city_region,
            addr.get("postcode"), addr.get("country"),
            _kv("Tel", addr.get("phone")), addr.get("email")))
    return (fallback_name, _flatten(
        cust.get("contact"), cust.get("address"), cust.get("postcode"), cust.get("country"),
        _kv("Tel", cust.get("phone")), _kv("Tel", cust.get("phone2")),
        _kv("Fax", cust.get("fax")), cust.get("email")))


def _flatten(*blocks) -> list[str]:
    """Split each block on newlines, drop blanks — a clean list of address/detail lines."""
    out = []
    for block in blocks:
        for line in (block or "").splitlines():
            if line.strip():
                out.append(line.strip())
    return out


def _party(pdf, x: float, top: float, width: float, heading: str, name: str,
           lines: list[str]) -> float:
    """Render a 'From'/'To' party column at (x, top) within ``width``; returns the ending Y."""
    y = top
    pdf.set_xy(x, y)
    pdf.set_font("Helvetica", "B", 7.5)
    pdf.set_text_color(120)
    pdf.cell(width, 4, heading.upper())
    y += 4
    pdf.set_xy(x, y)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(20)
    pdf.cell(width, 6, _s(name))
    y += 6
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(70)
    for line in lines:
        pdf.set_xy(x, y)
        pdf.cell(width, 5, _s(line))
        y += 5
    return y


def _join(c, *keys):
    return " ".join(c.get(k) or "" for k in keys).strip()


def _kv(label, value):
    return f"{label}: {value}" if value else ""
